# this image is just to compile typescript
FROM node:16-alpine
WORKDIR /usr/app
COPY . .

# install modules and build typescript
RUN npm ci
RUN npm run build

# remove dev dependencies
RUN npm prune --production

# remove typescript files and package-lock
RUN rm -rf src tsconfig.json package-lock.json
RUN find . -name \*.ts -type f -delete